<?php
// Update sv/site.php with about content
$svContent = str_replace(
    "return [",
    "return [
    'about_title' => 'Om Oss',
    'about_desc' => 'Lär känna vår historia, uppdrag och vision',
    'our_story' => 'Vår Historia',
    'story_title' => 'Tillsammans Skapar Vi Hopp för Dem som Behöver Det Mest',
    'story_p1' => 'Vår humanitära resa började från lidandets hjärta, där vi själva såg det akuta behovet av humanitärt stöd i drabbade områden. Vi startade med en tydlig vision: att ge hjälp och utvecklingsstöd till behövande familjer utan diskriminering.',
    'story_p2' => 'Genom våra lokala och internationella partnerskap har vi nått tusentals drabbade familjer med mat, medicinsk hjälp och tak över huvudet. Varje donation är ett nytt hopp om ett värdigt liv.',
    'story_p3' => 'Vi tror att humanitärt arbete är ett uppdrag som kräver transparens, trovärdighet och engagemang. Vi är engagerade i att hålla administrativa kostnader till ett minimum.',
    'mission_title' => 'Vårt Uppdrag',
    'mission_desc' => 'Att ge humanitärt stöd till dem som drabbats av konflikter och katastrofer, och stärka dem att leva med värdighet genom hållbara utvecklingsprogram.',
    'vision_title' => 'Vår Vision',
    'vision_desc' => 'En värld där ingen lider av hunger eller brist, där humanitära insatser förenas för att bygga motståndskraftiga samhällen.',
    'core_values' => 'Våra Värderingar',
    'values_title' => 'Principerna Vi Arbetar Efter',
    'value_transparency_title' => 'Transparens',
    'value_transparency_desc' => 'Vi arbetar med full transparens i insamling och användning av donationer och publicerar regelbundna rapporter.',
    'value_integrity_title' => 'Integritet',
    'value_integrity_desc' => 'Vi följer de högsta standarderna för integritet och yrkesetik i all vår verksamhet.',
    'value_impact_title' => 'Effekt',
    'value_impact_desc' => 'Vi strävar efter att uppnå maximal positiv effekt genom att rikta resurser dit behovet är störst.',
    'value_compassion_title' => 'Medkänsla',
    'value_compassion_desc' => 'Vi sätter mänskligheten i centrum för allt vi gör och behandlar alla med värdighet och respekt.',
    'our_partners' => 'Våra Partners',
    'partners_title' => 'Vem Vi Samarbetar Med',
    'partners_desc' => 'Vi är stolta över att samarbeta med lokala och internationella partners',
    'partner_placeholder' => 'Partner',
    'cta_title' => 'Var en Del av Förändringen',
    'cta_desc' => 'Din donation idag kan förändra en hel familjs liv. Följ med oss på denna givandets resa.',
    'nav_home' => 'Hem',",
    file_get_contents(__DIR__ . '/lang/sv/site.php')
);
file_put_contents(__DIR__ . '/lang/sv/site.php', $svContent);
echo "sv/site.php updated.\n";

// Create id/site.php
$idContent = "<?php

return [
    'about_title' => 'Tentang Kami',
    'about_desc' => 'Pelajari cerita, misi, dan visi kami',
    'our_story' => 'Cerita Kami',
    'story_title' => 'Bersama Kami Menciptakan Harapan bagi Mereka yang Membutuhkan',
    'story_p1' => 'Perjalanan kemanusiaan kami dimulai dari penderitaan, di mana kami menyaksikan langsung kebutuhan mendesak akan bantuan kemanusiaan di daerah yang terkena dampak. Kami memulai dengan visi yang jelas: memberikan bantuan dan dukungan pembangunan kepada keluarga yang membutuhkan tanpa diskriminasi.',
    'story_p2' => 'Melalui kemitraan lokal dan internasional kami, kami telah menjangkau ribuan keluarga yang terkena dampak, memberikan bantuan makanan, medis, dan tempat tinggal. Setiap donasi adalah harapan baru untuk kehidupan yang bermartabat.',
    'story_p3' => 'Kami percaya pekerjaan kemanusiaan adalah misi yang membutuhkan transparansi, kredibilitas, dan komitmen. Kami berkomitmen untuk menjaga biaya administrasi seminimal mungkin.',
    'mission_title' => 'Misi Kami',
    'mission_desc' => 'Memberikan bantuan kemanusiaan kepada mereka yang terkena dampak konflik dan bencana, memberdayakan mereka untuk hidup dengan martabat melalui program pembangunan berkelanjutan.',
    'vision_title' => 'Visi Kami',
    'vision_desc' => 'Dunia di mana tidak ada yang menderita kelaparan atau kekurangan, di mana upaya kemanusiaan bersatu untuk membangun komunitas yang tangguh.',
    'core_values' => 'Nilai-Nilai Kami',
    'values_title' => 'Prinsip yang Kami Kerjakan',
    'value_transparency_title' => 'Transparansi',
    'value_transparency_desc' => 'Kami beroperasi dengan transparansi penuh dalam mengumpulkan dan membelanjakan donasi.',
    'value_integrity_title' => 'Integritas',
    'value_integrity_desc' => 'Kami mematuhi standar integritas dan etika profesional tertinggi dalam semua urusan kami.',
    'value_impact_title' => 'Dampak',
    'value_impact_desc' => 'Kami berusaha mencapai dampak positif maksimal dengan mengarahkan sumber daya ke tempat yang paling membutuhkan.',
    'value_compassion_title' => 'Kasih Sayang',
    'value_compassion_desc' => 'Kami menempatkan kemanusiaan di pusat dari semua yang kami lakukan.',
    'our_partners' => 'Mitra Kami',
    'partners_title' => 'Dengan Siapa Kami Bekerja Sama',
    'partners_desc' => 'Kami bangga bekerja sama dengan mitra lokal dan internasional',
    'partner_placeholder' => 'Mitra',
    'cta_title' => 'Jadilah Bagian dari Perubahan',
    'cta_desc' => 'Donasi Anda hari ini dapat mengubah hidup satu keluarga. Bergabunglah dengan kami.',
    'nav_home' => 'Beranda',
    'nav_about' => 'Tentang Kami',
    'nav_projects' => 'Proyek',
    'nav_news' => 'Berita',
    'nav_donate' => 'Donasi',
    'nav_contact' => 'Kontak',
    'donate_now' => 'Donasi Sekarang',
    'read_more' => 'Baca Selengkapnya',
    'contribute' => 'Berkontribusi',
    'view_all' => 'Lihat Semua',
    'main_projects' => 'Proyek Utama',
    'announcements' => 'Pengumuman',
    'success_stories' => 'Kisah Sukses',
    'programs_title' => 'Program Kemanusiaan',
    'humanitarian_stats' => 'Statistik Situasi Kemanusiaan di Gaza',
    'about_us' => 'Tentang Kami',
    'contact_us' => 'Hubungi Kami',
    'contact_success' => 'Terima kasih! Pesan Anda telah diterima.',
    'donation_success' => 'Terima kasih atas donasi Anda! Kami akan menghubungi Anda untuk konfirmasi.',
    'donation_form' => 'Formulir Donasi',
    'full_name' => 'Nama Lengkap',
    'email' => 'Email',
    'amount' => 'Jumlah Donasi (USD)',
    'message' => 'Pesan (opsional)',
    'subject' => 'Subjek',
    'send_message' => 'Kirim Pesan',
    'complete_donation' => 'Selesaikan Donasi',
    'payment_methods' => 'Metode Pembayaran yang Diterima',
    'whatsapp' => 'WhatsApp',
    'all_rights' => 'Hak cipta dilindungi © Sahem',
];
";
file_put_contents(__DIR__ . '/lang/id/site.php', $idContent);
echo "id/site.php created.\n";
